version:
  version: 1.0.4
server:
  address: 127.0.0.1
  port: 8080
  #compression:
   #   enabled: true
    #  mime-types: application/json,application/xml,text/html,text/xml,text/plain
site:
    title: 北京麻将
    serverUrl: ws://127.0.0.1:8010/g
application:
    message: Hello, Andy

spring:
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

logging:
    level:
        org:
            springframework:
                web: INFO
debug:
    false


jdbc:
    url: jdbc:mysql://127.0.0.1:3306/boss?autoReconnect=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    maxNums: 20
    minNums: 5

weixin:
    appAppID:  #app 微信开发平台appid
    appAppsecret:  #app  微信开发平台appsecret
    appID: #app 微信公众平台appid
    appsecret: #app 微信公众平台appsecret
    clienttokenUrl: https://api.weixin.qq.com/cgi-bin/token
    jsticketUrl: https://api.weixin.qq.com/cgi-bin/ticket/getticket
    authorizeUrl: https://open.weixin.qq.com/connect/oauth2/authorize
    tokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token
    refresstokenUrl: https://api.weixin.qq.com/sns/oauth2/refresh_token
    getuserUrl: https://api.weixin.qq.com/sns/userinfo

#    siteUrl: http://gd.paipaimj.com
   # siteUrl: http://www.openmajiang.com
    siteUrl: http://127.0.0.1:8080
net:
    boss:
        address: 127.0.0.1
        port: 12100
    #    管理接口公钥
        publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCOLX6y_Ud7svHi4PDOUgQMhn9DrWjTU7che_8KOK0XoItY8NlAhVXdus82Xvs268O-GgmeVmOGwXfxrFgft5CCQx-okQM2_qbuKWH1IA3JRYbKz2Kt93wtHZHqSFmwtIcv3kxupbw9umqP8dBjsPUue9vHcbem3uys6e56FHvjowIDAQAB